repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: mojo-format
        name: Mojo Format
        entry: mojo format
        language: system
        types_or: [file]
        files: \.mojo$
