[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community", "https://repo.prefix.dev/jojo", "https://repo.prefix.dev/better-ffi", "https://repo.prefix.dev/better-mojo"]
description = "Add a short description here"
name = "uuid-mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = { cmd = "rattler-build build --recipe recipes/ -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }
package = { cmd = "mojo package src/uuid_mojo -o build/uuid_mojo.mojopkg"}


[dependencies]
max = ">=24.5.0,<25"
libuuid_ffi = ">=0.1.1,<0.2"

[feature.dev.dependencies]
rattler-build = "*"
