version: "3"

tasks:
  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}

  init:
    cmds:
      - magic project channel add "conda-forge"
      - magic project channel add "https://conda.modular.com/max"
      - magic project channel add "https://repo.prefix.dev/mojo-community"
      - magic project channel add "https://repo.prefix.dev/jojo"
      - magic project channel add "https://repo.prefix.dev/better-ffi"
      - magic project channel add "https://repo.prefix.dev/better-mojo"

  add:all:
    cmds:
      - magic add libuuid_ffi

  add:dev:
    aliases: [ "ad" ]
    cmds:
      - magic add rattler-build --feature dev
      - pixi global install rattler-build

  run:
    aliases: [ "r" ]
    cmds:
      - RUST_BACKTRACE=full magic run mojo src/main.mojo

  #
  # 打包 .conda, 待发布
  #
  build:
    aliases: [ "b" ]
    cmds:
      - mkdir -p build/
      - magic run build
      - open output/
    ignore_error: true

  clean:
    cmds:
      - rm -rf output/
    ignore_error: true

  clean:build:
    aliases: [ 'cb', 'bc' ]
    cmds:
      - task: clean
      - task: build

  #
  # ref: https://taskfile.dev/usage/#looping-over-variables
  #
  publish:
    aliases: [ "up", "pub", "pub:auto" ]
    vars:
      UP_PKGS:
        sh: find . -name "*.conda" -type f
    cmds:
      - echo {{ .UP_PKGS }}
      - for: { var: UP_PKGS }
        cmd:
          |
          magic run rattler-build upload prefix -c "better-mojo" \
            --api-key=$PREFIX_DEV_API_KEY \
            {{.ITEM}}
      - open https://prefix.dev/channels/better-mojo
    dir: output/

  #
  # 快捷发布：
  #
  clean:build:publish:
    aliases: [ 'quick', 'upc' ]
    cmds:
      - task: clean:build
      - task: up

  examples:init:
    aliases: [ "exi" ]
    cmds:
      - magic project channel add "conda-forge"
      - magic project channel add "https://conda.modular.com/max"
      - magic project channel add "https://repo.prefix.dev/mojo-community"
      - magic project channel add "https://repo.prefix.dev/jojo"
      - magic project channel add "https://repo.prefix.dev/better-ffi"
      - magic project channel add "https://repo.prefix.dev/better-mojo"
    dir: examples/try-uuid-mojo

  examples:add:
    aliases: [ "exa" ]
    cmds:
      - magic add uuid_mojo libuuid_ffi
    dir: examples/try-uuid-mojo

  examples:run:
    aliases: [ "exr" ]
    cmds:
      - magic run mojo src/main.mojo
    dir: examples/try-uuid-mojo



