[package]
name = "uuid-ffi"
version = "0.1.0"
edition = "2021"



[[bin]]
name = "v4"
path = "examples/v4.rs"


[[bin]]
name = "v7"
path = "examples/v7.rs"


[lib]
name = "uuid_ffi"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
uuid = { version = "1.10.0", features = ["v4", "v7"] }
libc = "0.2.159"
#libc = "0.2.159"

[build-dependencies]
cbindgen = "0.27.0"

