[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "uuid-ffi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = "cargo build"

[dependencies]
rust = ">=1.81.0,<2"
conda-build = ">=24.9.0,<25"
