[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "uuid-ffi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
