[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "libuuid-ffi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
release = "cargo build --release"
build = { cmd = "rattler-build build --recipe recipes/ -c https://conda.modular.com/max -c conda-forge --skip-existing=all" }
test = "RUST_LOG=info cargo test --lib"
check = "RUSTFLAGS='-Z sanitizer=leak' cargo +nightly build"

[dependencies]
rust = ">=1.81.0,<2"
conda-build = ">=24.9.0,<25"
