version: "3"

tasks:
  run:v4:
    aliases: [ "r4" ]
    cmds:
      - RUST_LOG=info cargo run --bin v4

  run:v7:
    aliases: [ "r7" ]
    cmds:
      - RUST_LOG=info cargo run --bin v4

  test:
    aliases: [ "t" ]
    cmds:
      - RUST_LOG=info cargo test --lib

  release:
    aliases: [ "rel" ]
    cmds:
      - RUST_BACKTRACE=full RUST_LOG=info cargo build --release # CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true

  clean:
    aliases: [ "cl", 'del' ]
    cmds:
      - cargo clean