# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
#
# ref:
#   - https://prefix-dev.github.io/rattler-build/latest/tutorials/rust/
#   - https://github.com/conda-forge/fcp-rust-feedstock/blob/main/recipe/meta.yaml#L17

context:
  version: "13.4.2"

package:
  name: "uuid_ffi"
  version: 0.1.1

source:
  - path: ../    # TODO X: 包含 cargo.toml 的路径!!!


build:
  script:
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml  # !(1)
    - $BUILD_PREFIX/bin/cargo install --locked --bins --root ${PREFIX} --path .
#

requirements:
  build:
    - ${{ compiler('rust') }}  # TODO X: rust toolchain
    - ${{ compiler('c') }}
    #    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

about:
  homepage: https://github.com/better-mojo/uuid
  license: MIT
  summary: "Core library for Jojo web framework - better-mojo"
  repository: https://github.com/better-mojo/uuid
