# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
#
# ref:
#   - https://prefix-dev.github.io/rattler-build/latest/tutorials/rust/
#   - https://github.com/conda-forge/fcp-rust-feedstock/blob/main/recipe/meta.yaml#L17

context:
  name: "libuuid_ffi" # TODO X: lib name
  version: "0.1.1"    # TODO X: lib version

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - path: ../ffigen/    # TODO X: 包含 cargo.toml 的路径!!!

#
# build dir:
#   - macos: packages/uuid-ffi/output/osx-arm64/uuid_ffi-0.1.1-h60d57d3_0/lib/aarch64-apple-darwin/release/libuuid_ffi.dylib
#
build:
  script:
    - if: osx
      then:
        #    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml  # !(1)
        #    - $BUILD_PREFIX/bin/cargo install --locked --bins --root ${PREFIX} --path .
        - mkdir -p ${PREFIX}/lib/tmp/
        - $BUILD_PREFIX/bin/cargo build --release --lib --target-dir ${PREFIX}/lib/tmp
        - cp ${PREFIX}/lib/tmp/aarch64-apple-darwin/release/${{ name }}.dylib ${PREFIX}/lib/
        #    - cp ${PREFIX}/lib/tmp/aarch64-apple-darwin/release/libuuid_ffi.a ${PREFIX}/lib/
        - rm -rf ${PREFIX}/lib/tmp/   # TODO X: if test build, disable this line.

    - if: linux
      then:
        - mkdir -p ${PREFIX}/lib/tmp/
        - $BUILD_PREFIX/bin/cargo build --release --lib --target-dir ${PREFIX}/lib/tmp
        - cp ${PREFIX}/lib/tmp/x86_64-unknown-linux-gnu/release/${{ name }}.so ${PREFIX}/lib/
        #        - cp ${PREFIX}/lib/tmp/x86_64-unknown-linux-gnu/release/libuuid_ffi.a ${PREFIX}/lib/
        - rm -rf ${PREFIX}/lib/tmp/

requirements:
  build:
    - ${{ compiler('rust') }}  # TODO X: rust toolchain
    - ${{ compiler('c') }}
    #    - ${{ stdlib('c') }}
#    - cargo-bundle-licenses

about:
  homepage: https://github.com/better-mojo/uuid
  license: MIT
  summary: "uuid-rs ffi for mojo"
  repository: https://github.com/better-mojo/uuid
