# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json


context:
    name: "uuid_mojo" # TODO X: lib name
    version: "0.1.3"    # TODO X: lib version

package:
    name: ${{ name|lower }}
    version: ${{ version }}

source:
    - path: ../src/uuid_mojo/  # TODO X: FIX HERE

build:
    script:
        - if: unix
          then:
              - mkdir -p ${PREFIX}/lib/mojo
              - magic run mojo package . -o ${PREFIX}/lib/mojo/${{ name }}.mojopkg
        - if: windows
          then:
              - echo 'not support yet!'


requirements:
    run:
        - max >=24.5.0
#        - gojo == 0.1.9

about:
    homepage: https://github.com/better-mojo/uuid
    license: MIT
    summary: "uuid-rs binding for mojo"
    repository: https://github.com/better-mojo/uuid
