# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
    version: "13.4.2"

package:
    name: "uuid_mojo"
    version: 0.1.3

source:
    - path: ../src/uuid_mojo/  # TODO X: FIX HERE

build:
    script:
        - mkdir -p ${PREFIX}/lib/mojo
        - magic run mojo package . -o ${PREFIX}/lib/mojo/uuid_mojo.mojopkg

requirements:
    run:
        - max >=24.5.0
#        - gojo == 0.1.9

about:
    homepage: https://github.com/better-mojo/uuid
    license: MIT
    summary: "uuid-rs binding for mojo"
    repository: https://github.com/better-mojo/uuid
