[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community", "https://repo.prefix.dev/jojo", "https://repo.prefix.dev/better-ffi", "https://repo.prefix.dev/better-mojo"]
description = "Add a short description here"
name = "try-uuid-mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
libuuid_ffi = ">=0.1.1,<0.2"
uuid_mojo = ">=0.1.3,<0.2"
