/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_UUID_FFI__
#define __RUST_UUID_FFI__
#ifdef __cplusplus
extern "C" {
#endif

/** \brief
 *  Frees a Rust-allocated string.
 */
void
free_rs_string (
    char * string);


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  生成新的 UUIDv4 到预分配缓冲区
 *
 *  # Safety
 *  - result 必须指向至少 size 字节的可用内存
 *  - size 必须至少为 37（36字符 + null终止符）
 *
 *  # 返回值
 *  - 成功：返回写入的字节数（包括 null 终止符，即 37）
 *  - 失败：返回 0（缓冲区太小）
 */
size_t
rs_gen_uuid_v4 (
    uint8_t * result,
    size_t size);

/** \brief
 *  批量生成 UUIDv4
 *
 *  # Arguments
 *  - results: 输出缓冲区，大小必须为 count * 37 字节
 *  - count: 要生成的 UUID 数量
 *  - buf_size: 缓冲区总大小
 *
 *  # Returns
 *  - 成功：实际生成的 UUID 数量
 *  - 失败：0（缓冲区太小）
 */
size_t
rs_gen_uuid_v4_batch (
    uint8_t * results,
    size_t count,
    size_t buf_size);

/** \brief
 *  生成新的 UUIDv7 到预分配缓冲区
 *
 *  # Safety
 *  - result 必须指向至少 size 字节的可用内存
 *  - size 必须至少为 37（36字符 + null终止符）
 *
 *  # 返回值
 *  - 成功：返回写入的字节数（包括 null 终止符，即 37）
 *  - 失败：返回 0（缓冲区太小）
 */
size_t
rs_gen_uuid_v7 (
    uint8_t * result,
    size_t size);

/** \brief
 *  批量生成 UUIDv7
 *
 *  # Arguments
 *  - results: 输出缓冲区，大小必须为 count * 37 字节
 *  - count: 要生成的 UUID 数量
 *  - buf_size: 缓冲区总大小
 *
 *  # Returns
 *  - 成功：实际生成的 UUID 数量
 *  - 失败：0（缓冲区太小）
 */
size_t
rs_gen_uuid_v7_batch (
    uint8_t * results,
    size_t count,
    size_t buf_size);

/** \brief
 *  生成新的 UUIDv4
 */
char *
rs_uuid_v4 (void);

/** \brief
 *  生成新的 UUIDv7
 */
char *
rs_uuid_v7 (void);

/** \brief
 *  比较两个 UUID
 *
 *  # Arguments
 *  - uuid1: 第一个 UUID 字符串
 *  - uuid2: 第二个 UUID 字符串
 *
 *  # Returns
 *  - uuid1 < uuid2: -1
 *  - uuid1 == uuid2: 0
 *  - uuid1 > uuid2: 1
 *  - 解析错误: -2
 */
int32_t
uuid_compare (
    char const * uuid1,
    char const * uuid2);

/** \brief
 *  解析 UUID 字符串为字节数组
 *
 *  # Arguments
 *  - uuid_str: UUID 字符串
 *  - result: 输出缓冲区，必须至少 16 字节
 *
 *  # Returns
 *  - 成功：0
 *  - 失败：-1（格式错误）
 */
int32_t
uuid_parse (
    char const * uuid_str,
    uint8_t * result);

typedef struct {
    uint8_t idx[16];
} uint8_16_array_t;

/** \brief
 *  格式化 UUID 字节数组为字符串
 *
 *  # Arguments
 *  - bytes: 16字节的 UUID 字节数组
 *
 *  # Returns
 *  - 成功：UUID 字符串
 *  - 失败："invalid_uuid"
 */
char *
uuid_to_string (
    uint8_16_array_t const * bytes);

/** \brief
 *  验证字符串是否为有效的 UUID
 *
 *  # Arguments
 *  - uuid_str: 要验证的字符串
 *
 *  # Returns
 *  - 有效：1
 *  - 无效：0
 */
int32_t
uuid_validate (
    char const * uuid_str);

/** \brief
 *  获取 UUID 版本号
 *
 *  # Arguments
 *  - uuid_str: UUID 字符串
 *
 *  # Returns
 *  - 成功：版本号 (1-8)
 *  - 失败：-1（格式错误或 nil UUID）
 */
int32_t
uuid_version (
    char const * uuid_str);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_UUID_FFI__ */
